import TemplateElement from "../template-element";
import { genHtmlTemplateEl } from "./util";

export const a          = genHtmlTemplateEl('a');
export const abbr       = genHtmlTemplateEl('abbr');
export const b          = genHtmlTemplateEl('b');
export const bdi        = genHtmlTemplateEl('bdi');
export const bdo        = genHtmlTemplateEl('bdo');
export const br         = genHtmlTemplateEl('br');
export const cite       = genHtmlTemplateEl('cite');
export const code       = genHtmlTemplateEl('code');
export const data       = genHtmlTemplateEl('data');
export const dfn        = genHtmlTemplateEl('dfn');
export const em         = genHtmlTemplateEl('em');
export const i          = genHtmlTemplateEl('i');
export const kbd        = genHtmlTemplateEl('kbd');
export const mark       = genHtmlTemplateEl('mark');
export const q          = genHtmlTemplateEl('q');
export const rp         = genHtmlTemplateEl('rp');
export const rt         = genHtmlTemplateEl('rt');
export const ruby       = genHtmlTemplateEl('ruby');
export const s          = genHtmlTemplateEl('s');
export const samp       = genHtmlTemplateEl('samp');
export const small      = genHtmlTemplateEl('small');
export const span       = genHtmlTemplateEl('span');
export const style      = genHtmlTemplateEl('style');
export const sub        = genHtmlTemplateEl('sub');
export const sup        = genHtmlTemplateEl('sup');
export const time       = genHtmlTemplateEl('time');
export const u          = genHtmlTemplateEl('u');
export const var_       = genHtmlTemplateEl('var');
export const wbr        = genHtmlTemplateEl('wbr');
export const strong     = genHtmlTemplateEl('strong');
