import TemplateElement, { TemplateElementChildren, TemplateElementParams } from "./template-element";

type HTMLTemplateElement<T extends keyof HTMLElementTagNameMap> = (
  childrenOrParams?: TemplateElementChildren |
    TemplateElementParams<HTMLElementTagNameMap[T]>,
  children?: TemplateElementChildren,
) => TemplateElement<HTMLElementTagNameMap[T]>;

/**
 * A collection of functions that create a TemplateElement for all standard html elements.
 *
 * @example
 * ```typescript
 * class Example extends Component {
 *   render = () => [
 *     h.div({ attrs: { id: 'hi' }}, h.span('A child <span> element'))
 *   ]
 * }
 * ```
 */
const h: { [key in keyof HTMLElementTagNameMap]: HTMLTemplateElement<key> } =  {
  a          : TemplateElement.fromBuiltin('a'),
  abbr       : TemplateElement.fromBuiltin('abbr'),
  address    : TemplateElement.fromBuiltin('address'),
  area       : TemplateElement.fromBuiltin('area'),
  article    : TemplateElement.fromBuiltin('article'),
  aside      : TemplateElement.fromBuiltin('aside'),
  audio      : TemplateElement.fromBuiltin('audio'),
  b          : TemplateElement.fromBuiltin('b'),
  base       : TemplateElement.fromBuiltin('base'),
  bdi        : TemplateElement.fromBuiltin('bdi'),
  bdo        : TemplateElement.fromBuiltin('bdo'),
  blockquote : TemplateElement.fromBuiltin('blockquote'),
  body       : TemplateElement.fromBuiltin('body'),
  br         : TemplateElement.fromBuiltin('br'),
  button     : TemplateElement.fromBuiltin('button'),
  canvas     : TemplateElement.fromBuiltin('canvas'),
  caption    : TemplateElement.fromBuiltin('caption'),
  cite       : TemplateElement.fromBuiltin('cite'),
  code       : TemplateElement.fromBuiltin('code'),
  col        : TemplateElement.fromBuiltin('col'),
  colgroup   : TemplateElement.fromBuiltin('colgroup'),
  data       : TemplateElement.fromBuiltin('data'),
  datalist   : TemplateElement.fromBuiltin('datalist'),
  dd         : TemplateElement.fromBuiltin('dd'),
  del        : TemplateElement.fromBuiltin('del'),
  details    : TemplateElement.fromBuiltin('details'),
  dfn        : TemplateElement.fromBuiltin('dfn'),
  dialog     : TemplateElement.fromBuiltin('dialog'),
  div        : TemplateElement.fromBuiltin('div'),
  dl         : TemplateElement.fromBuiltin('dl'),
  dt         : TemplateElement.fromBuiltin('dt'),
  em         : TemplateElement.fromBuiltin('em'),
  embed      : TemplateElement.fromBuiltin('embed'),
  fieldset   : TemplateElement.fromBuiltin('fieldset'),
  figcaption : TemplateElement.fromBuiltin('figcaption'),
  figure     : TemplateElement.fromBuiltin('figure'),
  footer     : TemplateElement.fromBuiltin('footer'),
  form       : TemplateElement.fromBuiltin('form'),
  h1         : TemplateElement.fromBuiltin('h1'),
  h2         : TemplateElement.fromBuiltin('h2'),
  h3         : TemplateElement.fromBuiltin('h3'),
  h4         : TemplateElement.fromBuiltin('h4'),
  h5         : TemplateElement.fromBuiltin('h5'),
  h6         : TemplateElement.fromBuiltin('h6'),
  head       : TemplateElement.fromBuiltin('head'),
  header     : TemplateElement.fromBuiltin('header'),
  hgroup     : TemplateElement.fromBuiltin('hgroup'),
  hr         : TemplateElement.fromBuiltin('hr'),
  html       : TemplateElement.fromBuiltin('html'),
  i          : TemplateElement.fromBuiltin('i'),
  iframe     : TemplateElement.fromBuiltin('iframe'),
  img        : TemplateElement.fromBuiltin('img'),
  input      : TemplateElement.fromBuiltin('input'),
  ins        : TemplateElement.fromBuiltin('ins'),
  kbd        : TemplateElement.fromBuiltin('kbd'),
  label      : TemplateElement.fromBuiltin('label'),
  legend     : TemplateElement.fromBuiltin('legend'),
  li         : TemplateElement.fromBuiltin('li'),
  link       : TemplateElement.fromBuiltin('link'),
  main       : TemplateElement.fromBuiltin('main'),
  map        : TemplateElement.fromBuiltin('map'),
  mark       : TemplateElement.fromBuiltin('mark'),
  menu       : TemplateElement.fromBuiltin('menu'),
  meta       : TemplateElement.fromBuiltin('meta'),
  meter      : TemplateElement.fromBuiltin('meter'),
  nav        : TemplateElement.fromBuiltin('nav'),
  noscript   : TemplateElement.fromBuiltin('noscript'),
  object     : TemplateElement.fromBuiltin('object'),
  ol         : TemplateElement.fromBuiltin('ol'),
  optgroup   : TemplateElement.fromBuiltin('optgroup'),
  option     : TemplateElement.fromBuiltin('option'),
  output     : TemplateElement.fromBuiltin('output'),
  p          : TemplateElement.fromBuiltin('p'),
  picture    : TemplateElement.fromBuiltin('picture'),
  pre        : TemplateElement.fromBuiltin('pre'),
  progress   : TemplateElement.fromBuiltin('progress'),
  q          : TemplateElement.fromBuiltin('q'),
  rp         : TemplateElement.fromBuiltin('rp'),
  rt         : TemplateElement.fromBuiltin('rt'),
  ruby       : TemplateElement.fromBuiltin('ruby'),
  s          : TemplateElement.fromBuiltin('s'),
  samp       : TemplateElement.fromBuiltin('samp'),
  script     : TemplateElement.fromBuiltin('script'),
  section    : TemplateElement.fromBuiltin('section'),
  select     : TemplateElement.fromBuiltin('select'),
  slot       : TemplateElement.fromBuiltin('slot'),
  small      : TemplateElement.fromBuiltin('small'),
  source     : TemplateElement.fromBuiltin('source'),
  span       : TemplateElement.fromBuiltin('span'),
  strong     : TemplateElement.fromBuiltin('strong'),
  style      : TemplateElement.fromBuiltin('style'),
  sub        : TemplateElement.fromBuiltin('sub'),
  summary    : TemplateElement.fromBuiltin('summary'),
  sup        : TemplateElement.fromBuiltin('sup'),
  table      : TemplateElement.fromBuiltin('table'),
  tbody      : TemplateElement.fromBuiltin('tbody'),
  td         : TemplateElement.fromBuiltin('td'),
  template   : TemplateElement.fromBuiltin('template'),
  textarea   : TemplateElement.fromBuiltin('textarea'),
  tfoot      : TemplateElement.fromBuiltin('tfoot'),
  th         : TemplateElement.fromBuiltin('th'),
  thead      : TemplateElement.fromBuiltin('thead'),
  time       : TemplateElement.fromBuiltin('time'),
  title      : TemplateElement.fromBuiltin('title'),
  tr         : TemplateElement.fromBuiltin('tr'),
  track      : TemplateElement.fromBuiltin('track'),
  u          : TemplateElement.fromBuiltin('u'),
  ul         : TemplateElement.fromBuiltin('ul'),
  var        : TemplateElement.fromBuiltin('var'),
  video      : TemplateElement.fromBuiltin('video'),
  wbr        : TemplateElement.fromBuiltin('wbr'),
}

export default h;
