baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Mvui'
theme = 'hugo-book'

[params]
    BookTheme = 'auto'
    BookSection = 'docs'
    BookLogo = 'icon.svg'


[markup]
    [markup.highlight]
        style = 'dracula'
        tabWidth = 2

    [markup.goldmark.renderer]
        unsafe = true

[module]
    [[module.mounts]]
        source="../core/dist/minified"
        target="static/js/mvui/core"

    [[module.mounts]]
        source="../stdlib/dist/minified"
        target="static/js/mvui/stdlib"

    [[module.mounts]]
        source="static"
        target="static"
